# Generated by Django 4.2.7 on 2026-03-13 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voice_recognition', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAuditRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('model_name', models.CharField(blank=True, max_length=150)),
                ('endpoint_name', models.CharField(choices=[('incident-analysis', 'Incident Analysis'), ('incident-triage', 'Incident Triage')], max_length=30)),
                ('dry_run', models.BooleanField(default=True)),
                ('success', models.BooleanField(default=False)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('moderation_flags', models.JSONField(blank=True, default=dict)),
                ('request_metadata', models.JSONField(blank=True, default=dict)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('external_request_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_audit_records', to='incidents.incident')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_audit_records', to=settings.AUTH_USER_MODEL)),
                ('voice_recording', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_audit_records', to='voice_recognition.voicerecording')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', '-created_at'], name='ai_gateway__provide_65c8b4_idx'), models.Index(fields=['endpoint_name', '-created_at'], name='ai_gateway__endpoin_61e492_idx')],
            },
        ),
    ]
