# Generated by Django 4.2.7 on 2026-03-13 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_gateway', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIFullAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_use_all_features', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grantee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_full_access_grants_received', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_full_access_grants_issued', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='aifullaccessgrant',
            index=models.Index(fields=['grantee', 'is_active'], name='ai_gateway__grantee_c55892_idx'),
        ),
        migrations.AddIndex(
            model_name='aifullaccessgrant',
            index=models.Index(fields=['owner', 'is_active'], name='ai_gateway__owner_i_2d2a52_idx'),
        ),
        migrations.AddConstraint(
            model_name='aifullaccessgrant',
            constraint=models.UniqueConstraint(fields=('owner', 'grantee'), name='unique_owner_grantee_ai_access'),
        ),
    ]
