# Generated by Django 4.2.7 on 2026-03-13 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_gateway', '0002_aifullaccessgrant'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aifullaccessgrant',
            new_name='ai_gateway__grantee_da697d_idx',
            old_name='ai_gateway__grantee_c55892_idx',
        ),
        migrations.RenameIndex(
            model_name='aifullaccessgrant',
            new_name='ai_gateway__owner_i_08e707_idx',
            old_name='ai_gateway__owner_i_2d2a52_idx',
        ),
    ]
