# Generated by Django 4.2.7 on 2026-03-13 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_gateway', '0003_rename_ai_gateway__grantee_c55892_idx_ai_gateway__grantee_da697d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIOwnerInboxThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('last_message_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_owner_inbox_threads_assigned', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_owner_inbox_threads_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_message_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIOwnerInboxMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_role', models.CharField(choices=[('user', 'User'), ('owner', 'Owner'), ('system', 'System')], max_length=20)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_owner_inbox_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_gateway.aiownerinboxthread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aiownerinboxthread',
            index=models.Index(fields=['requester', '-last_message_at'], name='ai_gateway__request_90b1f4_idx'),
        ),
        migrations.AddIndex(
            model_name='aiownerinboxthread',
            index=models.Index(fields=['assigned_owner', '-last_message_at'], name='ai_gateway__assigne_9d1284_idx'),
        ),
        migrations.AddIndex(
            model_name='aiownerinboxmessage',
            index=models.Index(fields=['thread', 'created_at'], name='ai_gateway__thread__83550b_idx'),
        ),
    ]
