# Generated by Django 4.2.7 on 2026-03-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_gateway', '0004_aiownerinboxthread_aiownerinboxmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiownerinboxthread',
            name='owner_last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiownerinboxthread',
            name='requester_last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
